### ISSUE TITLE
CI fails for py33

### ISSUE THREAD

**Issue by adelton** [strongswan/swidGenerator#49]
I have Travis CI cron job set for my fork of swidGenerator repo. Lately, the tests fail for master (== 0d0941d261925cc01638e88df748c0f2c4395131) for the Python: 3.3: https://travis-ci.org/adelton/swidGenerator/builds/428317519 with error
```
$ tox
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/bin/tox", line 7, in <module>
    from tox import cmdline
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tox/__init__.py", line 10, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 90, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
```

Something has likely changed somewhere external to swidGenerator because the same commit passed a month ago, both in my clone https://travis-ci.org/adelton/swidGenerator/builds/413453444 and in upstream: https://travis-ci.org/strongswan/swidGenerator/builds/412677830

**Comment by tobiasbrunner** [comment]
Probably related to 9da44c927cbe05bee032f5f9996288d12f3ce0c2 somehow.

**Comment by tobiasbrunner** [comment]
I pushed a fix to the _50-hierarchic-root_ branch, which removes support for Python 3.3 (which was EOL for over a year) and adds testing with Python 3.7. The docker images used for the integration tests I've updated accordingly (see https://github.com/strongswan/swidGenerator-dockerimages).
